In [1]:
from gensim.models import Word2Vec,KeyedVectors
import gensim.downloader as api

In [ ]:
# skip gram technique
model = api.load("word2vec-google-news-300")

This model is trained over the google news data

The dimension of this model(number of neuron in hidden layer)=300

In [3]:
model["sunny"]

array([ 1.59179688e-01,  1.07910156e-01,  3.71093750e-02,  1.61132812e-01,
        3.02734375e-01, -3.35937500e-01, -3.83300781e-02, -1.32751465e-03,
       -8.69140625e-02,  2.25585938e-01,  2.23388672e-02,  1.35742188e-01,
       -1.04003906e-01,  1.73828125e-01,  5.46875000e-02,  1.13769531e-01,
       -1.53320312e-01,  2.29492188e-01,  1.13769531e-01,  1.61132812e-02,
       -1.46484375e-01,  5.07812500e-01, -1.08886719e-01, -1.59179688e-01,
       -9.37500000e-02, -6.64062500e-02,  1.90429688e-01,  2.49023438e-01,
       -1.08398438e-01,  2.00195312e-01, -2.19726562e-01,  8.83789062e-02,
        4.98046875e-02,  4.27246094e-02, -3.02734375e-01, -1.64062500e-01,
       -9.86328125e-02, -2.61718750e-01,  1.49414062e-01,  2.12890625e-01,
        2.38281250e-01, -1.50390625e-01,  1.82617188e-01,  1.18408203e-02,
        1.85546875e-02, -1.41601562e-01, -1.41601562e-01,  3.14941406e-02,
       -2.50000000e-01,  2.55859375e-01,  2.53906250e-01,  3.69140625e-01,
        4.43359375e-01,  

In [4]:
len(model["sunny"])

300

In [5]:
model["sunny savita"]

KeyError: "Key 'sunny savita' not present"

In [6]:
model["men"]

array([-4.78515625e-02,  1.66992188e-01,  7.81250000e-02,  2.10571289e-03,
        2.25585938e-01, -2.25585938e-01, -2.09960938e-01, -3.73535156e-02,
       -1.85546875e-02,  1.94335938e-01, -3.00292969e-02, -1.77734375e-01,
        5.20019531e-02,  1.33789062e-01, -1.13769531e-01,  1.10351562e-01,
       -3.27148438e-02,  2.89916992e-03,  9.88769531e-03,  9.27734375e-02,
       -2.19726562e-01, -2.47802734e-02, -8.59375000e-02, -2.67578125e-01,
       -2.51464844e-02, -2.55859375e-01, -1.61132812e-01,  2.53906250e-01,
        5.24902344e-02, -1.00097656e-02,  1.82617188e-01,  7.61718750e-02,
       -1.60980225e-03, -3.10058594e-02, -3.32031250e-02,  1.81640625e-01,
       -3.88183594e-02, -1.83593750e-01, -8.64257812e-02,  2.20703125e-01,
       -7.11059570e-03,  8.60595703e-03,  1.73828125e-01, -9.27734375e-02,
        1.25000000e-01, -1.28906250e-01, -4.85839844e-02, -1.21093750e-01,
        8.00781250e-02,  1.05957031e-01,  1.42578125e-01,  6.78710938e-02,
        6.29882812e-02, -

In [7]:
model.most_similar("men")

[('women', 0.767493724822998),
 ('Men', 0.6301247477531433),
 ('males', 0.6242231130599976),
 ('mens', 0.5807526707649231),
 ('boys', 0.5781347751617432),
 ('man', 0.5489763021469116),
 ('females', 0.5481874346733093),
 ('teenagers', 0.5462744832038879),
 ('girls', 0.540932834148407),
 ('ladies', 0.5234237909317017)]

In [8]:
model.most_similar("man")

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686),
 ('suspected_purse_snatcher', 0.571636438369751),
 ('robber', 0.5585119128227234),
 ('Robbery_suspect', 0.5584409832954407),
 ('teen_ager', 0.5549196600914001),
 ('men', 0.5489763021469116)]

In [9]:
model.most_similar("cricket")

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [ ]:
model.similarity("man","woman")

0.76640123

In [11]:
model.similarity("man","python")

0.2097966

In [12]:
model.similarity("man","man")

1.0

In [13]:
model.similarity("happy","joy")

0.35500747

In [14]:
model.similarity("python","java")

0.12539075

In [15]:
model.similarity("sunny","sunny")

1.0

In [16]:
model.similarity("sunny","Sunny")

0.43010473

In [17]:
model.similarity("bullet","murder")

0.16978478

In [18]:
model.doesnt_match(["PHP","JAVA","DOG","C++"])

'DOG'

In [19]:
vec=model["king"] - model["man"] + model["woman"]
vec

array([ 4.29687500e-02, -1.78222656e-01, -1.29089355e-01,  1.15234375e-01,
        2.68554688e-03, -1.02294922e-01,  1.95800781e-01, -1.79504395e-01,
        1.95312500e-02,  4.09919739e-01, -3.68164062e-01, -3.96484375e-01,
       -1.56738281e-01,  1.46484375e-03, -9.30175781e-02, -1.16455078e-01,
       -5.51757812e-02, -1.07574463e-01,  7.91015625e-02,  1.98974609e-01,
        2.38525391e-01,  6.34002686e-02, -2.17285156e-02,  0.00000000e+00,
        4.72412109e-02, -2.17773438e-01, -3.44726562e-01,  6.37207031e-02,
        3.16406250e-01, -1.97631836e-01,  8.59375000e-02, -8.11767578e-02,
       -3.71093750e-02,  3.15551758e-01, -3.41796875e-01, -4.68750000e-02,
        9.76562500e-02,  8.39843750e-02, -9.71679688e-02,  5.17578125e-02,
       -5.00488281e-02, -2.20947266e-01,  2.29492188e-01,  1.26403809e-01,
        2.49023438e-01,  2.09960938e-02, -1.09863281e-01,  5.81054688e-02,
       -3.35693359e-02,  1.29577637e-01,  2.41699219e-02,  3.48129272e-02,
       -2.60009766e-01,  

In [20]:
model.most_similar([vec])

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [32]:
model["chatgpt"]

KeyError: "Key 'chatgpt' not present"

### average wrod2vec

sentence = "I love machine leaning"

sentence -> vector? 

average word2vec concept

first -> create a vector for each word in the sentence

then -> take the average of all the vectors to get a single vector representation for the entire sentence


In [21]:
sentence = "I love machine leaning"


In [22]:
sentence.lower().split()

['i', 'love', 'machine', 'leaning']

In [23]:
words=sentence.lower().split()

In [24]:
word_vectors = []

In [25]:
for word in words:
    print(word)
    word_vectors.append(model[word])

i
love
machine
leaning


In [26]:
word_vectors

[array([-2.25585938e-01, -1.95312500e-02,  9.08203125e-02,  2.37304688e-01,
        -2.92968750e-02,  9.32617188e-02, -5.88378906e-02, -4.10156250e-02,
         5.22460938e-02,  2.00195312e-02, -3.44238281e-02, -2.91015625e-01,
        -2.61718750e-01, -1.90429688e-01,  3.85742188e-02,  8.30078125e-03,
         3.14941406e-02,  7.47070312e-02,  1.14746094e-01,  1.24511719e-02,
        -2.11914062e-01,  1.28906250e-01,  2.55859375e-01,  1.08886719e-01,
        -7.03125000e-02,  1.60156250e-01, -4.00390625e-01, -1.16699219e-01,
        -3.22265625e-02, -6.73828125e-02,  1.55273438e-01,  1.25000000e-01,
        -6.22558594e-02,  3.56445312e-02, -1.79687500e-01,  1.58203125e-01,
        -2.53906250e-01,  1.74804688e-01, -1.18164062e-01, -2.19726562e-03,
         1.49536133e-02, -5.71289062e-02,  2.39257812e-01,  1.36718750e-01,
         1.47460938e-01,  7.08007812e-02,  1.72851562e-01, -2.38281250e-01,
        -5.71289062e-02, -1.04492188e-01,  2.23388672e-02,  8.74023438e-02,
         1.4

In [29]:
import numpy as np
sentence_vector = np.mean(word_vectors,axis=0)
sentence_vector

array([ 0.08654785, -0.02920532,  0.01934814,  0.10394287, -0.07623291,
        0.13287354,  0.02923584, -0.07543945,  0.03479004,  0.05236816,
        0.00656128, -0.12268066, -0.08807373, -0.05981445, -0.01647949,
        0.04772949, -0.02679443,  0.15710449,  0.12103271, -0.06155396,
       -0.00863647,  0.17810059,  0.06201172,  0.0769043 ,  0.08166504,
       -0.02807617, -0.21960449,  0.08349609,  0.0838623 , -0.10852051,
        0.11303711,  0.00939941, -0.02876282,  0.1697998 , -0.02441406,
       -0.02575684, -0.01086426,  0.15637207,  0.01385117,  0.04760742,
        0.09101868, -0.1036377 ,  0.13903809,  0.00680542,  0.02758789,
        0.00109863,  0.00524902, -0.06317139,  0.03457642,  0.01861572,
       -0.04568481,  0.05419922,  0.00042725, -0.03565979, -0.00720215,
        0.1730957 ,  0.06060791, -0.03153229, -0.04133987, -0.09280396,
       -0.00549316,  0.06864929, -0.17858887, -0.07159424,  0.03771973,
       -0.15283203, -0.10876465,  0.00180435, -0.07566452,  0.08

In [31]:
sentence_vector.shape

(300,)

word2vec -> every word into the KeyedVectors

avg word2vec -> every sentence into a vector

now this technique is old, 

will see the sota(transformer based tech in next class)