In [1]:
print("all ok")

all ok


### One Hot Encoding

In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [3]:
documents = ["people watch movie", 
             "people watch cricket", 
             "people like movie", 
             "people like cricket"]

In [4]:
tokens = [sentence.lower().split() for sentence in documents]

In [5]:
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

In [6]:
all_words = [[word] for sentence in tokens for word in sentence]

In [7]:
all_words

[['people'],
 ['watch'],
 ['movie'],
 ['people'],
 ['watch'],
 ['cricket'],
 ['people'],
 ['like'],
 ['movie'],
 ['people'],
 ['like'],
 ['cricket']]

In [11]:
type(all_words)

list

In [8]:
encoder = OneHotEncoder(sparse_output=False)

#### sparse_output=False means the encoder returns a NumPy array instead of a sparse matrix. This makes the output easier
https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

In [9]:
encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [10]:
print("Vocabulary:", encoder.categories_[0])

Vocabulary: ['cricket' 'like' 'movie' 'people' 'watch']


In [13]:
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

In [15]:
for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print( "Encoded:\n", encoded_sentence)


Sentence: ['people', 'watch', 'movie']
Encoded:
 [[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'watch', 'cricket']
Encoded:
 [[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

Sentence: ['people', 'like', 'movie']
Encoded:
 [[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'like', 'cricket']
Encoded:
 [[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


### Bag of Words
https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html#sklearn.feature_extraction.text.CountVectorizer

In [1]:
from sklearn.feature_extraction.text import CountVectorizer

In [2]:
documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket", 
             "people like movie and like movie a lot", 
             "people like cricket"]

### AIM: Covert Data into Number

In [3]:
bow = CountVectorizer()

In [4]:
bow_matrix = bow.fit_transform(documents)

In [5]:
bow_matrix

<4x8 sparse matrix of type '<class 'numpy.int64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [6]:
print("BOW Matrix:\n", bow_matrix.toarray())

BOW Matrix:
 [[1 1 0 0 0 2 1 2]
 [0 1 2 0 0 0 1 2]
 [0 1 0 2 1 2 1 0]
 [0 0 1 1 0 0 1 0]]


In [7]:
print('Vocabulary:', bow.get_feature_names_out())

Vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']


In [8]:
bow.fit(documents)

CountVectorizer()

In [9]:
documents

['people watch movie and watch movie again',
 'people watch cricket and watch cricket',
 'people like movie and like movie a lot',
 'people like cricket']

In [10]:
bow.transform(documents).toarray()

array([[1, 1, 0, 0, 0, 2, 1, 2],
       [0, 1, 2, 0, 0, 0, 1, 2],
       [0, 1, 0, 2, 1, 2, 1, 0],
       [0, 0, 1, 1, 0, 0, 1, 0]], dtype=int64)

In [11]:
document=["lion is the king of the jungle"]

In [13]:
bow.transform(document).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

### TF-IDF Practical

In [38]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [39]:
documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket", 
             "people like movie and like movie a lot", 
             "people like cricket"]

In [40]:
tf_idf = TfidfVectorizer()

In [41]:
tf_idf_vector=tf_idf.fit_transform(documents)

In [42]:
tf_idf_vector

<4x8 sparse matrix of type '<class 'numpy.float64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [43]:
tf_idf_vector.toarray()

array([[0.38771136, 0.24747114, 0.        , 0.        , 0.        ,
        0.61135218, 0.20232387, 0.61135218],
       [0.        , 0.2684707 , 0.66322944, 0.        , 0.        ,
        0.        , 0.21949239, 0.66322944],
       [0.        , 0.24747114, 0.        , 0.61135218, 0.38771136,
        0.61135218, 0.20232387, 0.        ],
       [0.        , 0.        , 0.64043405, 0.64043405, 0.        ,
        0.        , 0.42389674, 0.        ]])

In [44]:
for vector in tf_idf_vector.toarray():
    print("\nTF-IDF Vector:\n", vector)


TF-IDF Vector:
 [0.38771136 0.24747114 0.         0.         0.         0.61135218
 0.20232387 0.61135218]

TF-IDF Vector:
 [0.         0.2684707  0.66322944 0.         0.         0.
 0.21949239 0.66322944]

TF-IDF Vector:
 [0.         0.24747114 0.         0.61135218 0.38771136 0.61135218
 0.20232387 0.        ]

TF-IDF Vector:
 [0.         0.         0.64043405 0.64043405 0.         0.
 0.42389674 0.        ]


In [47]:
print("Vocabulary:", tf_idf.get_feature_names_out())

Vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']
